# Dockerfile1
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app

# Accept dynamic argument
ARG APP_VERSION
ENV APP_VERSION=${APP_VERSION}

# Set environment variable
ENV ENVIRONMENT=production

COPY . .

RUN pip install --trusted-host pypi.python.org -r requirements.txt

CMD ["python", "app.py"]

#=============================
##FROM python:3.12-slim
##WORKDIR /app
##COPY . /app
##RUN pip install --trusted-host pypi.python.org -r requirements.txt
##EXPOSE 80
##ENV NAME World
##CMD ["python", "app.py"]
